### ISSUE TITLE
YTD and Yearly My Artist/My Tracks stats

### ISSUE THREAD

**Issue by Strijdhagen** [alexolivero/Obscurify#1]
Hi Alex,

Love the website, especially my own listening statistics.
Is there any way you could add a list of YTD, or even better a slider for most played artists/tracks stats of every year?
Spotify used to publish these every year but they don't give numbers anymore since last year.

**Comment by alexolivero** [comment]
Hey thanks!

I wish there was. Spotify doesn't release information that specific. What
you see on the website is about as in-depth as it gets with the API they
provide.

Alex

**Comment by Strijdhagen** [comment]
That's a shame! So the 6 weeks time is hard coded and not a variable you chose?

**Comment by alexolivero** [comment]
That's correct. As awesome as it is, Spotify limits their API just enough
to be annoying.
