### ISSUE TITLE
Authorization Scope

### ISSUE THREAD

**Issue by cowglow** [alexolivero/Obscurify#10]
This is more of a question:

Does the Authorization scope need to include "Create, edit and follow"??

Message on authentication screen reads: 
```
Take actions in Spotify on your behalf
Create, edit, and follow private playlists
Create, edit, and follow playlists
```
Is this necessary, can it be changed?

**Comment by CodeF0x** [comment]
I think it is because Obscurify provides a feature that lets you add a playlist with song recommendations based on your listening habits to your account.
