### ISSUE TITLE
track-list-header: artistNav and trackNav selection confusing

### ISSUE THREAD

**Issue by Tuaniwan** [alexolivero/Obscurify#2]
Hello, thanks for making such a great app alex!

This is not a huge issue, and it might not even be, but in this section of the website:

<img src="https://image.prntscr.com/image/uUnsVHPERkGHODBMhi2bGg.jpeg">

It's a little bit confusing to know which one is selected if you just look at the two titles.

I use the site a few times a month and I have been for a few months. I love the new update, the UI is amazing. But every time I come back to the site, I notice those 2 titles and I have to figure out which is the one that's selected?  The reason for this is that I usually relate underlined text with the one being currently selected. Now the unselected one is not underlined, but it still confuses my eye.

Let me just repeat: this is not a major issue, just a suggestion, it might be just me.

Anyway, if this is recognized as a potential issue, I'm willing to propose a few alternatives and develop it as well. Even if it's not, I'm still going to use it!

Thanks!

**Comment by alexolivero** [comment]
Hey Tuaniwan, this is some great feedback. I agree with you, it could be more clear. I've just made the crossed-out header to have a 0.5 opacity, that should improve it - but if you have a better idea, let me know.
