### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by lukeschunk** [alexolivero/Obscurify#3]
Just want to say - ❤️the app, a lot, i've been showing all my friends. Also love that spotify is so open with their APIs and data. 

You know what would be an awesome feature is seeing your happiness/danceability/etc over time. Obviously not a quick thing to implement, but I think people would love to see that. I might try to pull this down and run it, but i haven't written angular in a while so I could be a little rusty.

**Comment by alexolivero** [comment]
Thanks Luke! I appreciate that.

I definitely agree, that was a feature I always wanted to implement but never got around to it. It would absolutely be possible and interesting to see.

Would be really cool if you did pull it and tried to play around with it. I would love to know how much sense the code makes to someone else.
