### ISSUE TITLE
Apple music support?

### ISSUE THREAD

**Issue by sdhull** [alexolivero/Obscurify#8]
I realize this would be a big effort. I believe Apple Music [has a js api](https://developer.apple.com/documentation/musickitjs). I have no idea if it has all the APIs you would need 😬

**Comment by alexolivero** [comment]
Hello, thanks for the feedback!
I've checked into Apple Music and unfortunately their API doesn't offer the same level of information Spotify's does, such as the popularity rating on all artists & tracks. Until the day their API offers more, Obscurify on Apple Music won't be feasible - but I will be keeping an eye on it.
