### ISSUE TITLE
Issues with the newest version

### ISSUE THREAD

**Issue by Nezia1** [alexolivero/Obscurify#9]
I found some stuff that could be improved with the newest version you guys just posted: 
- The github link disappeared. Was it intentional or did you forget to add it back? I think it would be cool to add it since you mention the project being open source in your privacy policy.
- The current top artists / tracks are way too low, there's a lot of space not used. Maybe you could remove some of the color stripes? I thought the website was empty when I first visited it, which is why I went on the Github to open an issue about it. It was kind of weird since I've been using the app for quite some time now.
- This is more of a UX thing, but I think the "Switch Lists" button is redundant because of the toggle between artists / songs and the bullet point list.

Regardless, I think the new version looks really good! Just these are the small improvements I found that you could probably update. I don't really know Angular, I'm more versed with other front-end frameworks, but I could probably tackle some of these issues?

**Comment by alexolivero** [comment]
Hey Anthony,

Thanks for the post. Really nice points

   - We will replace the GitHub link shortly
   - What do you mean they are way too low, and have a lot of unused space?
   Can you elaborate on that?
   - The "Switch List" button was supposed to only be there on mobile, it
   should be gone on desktop now

Appreciate the feedback, hit us back if you see anything else!

**Comment by Nezia1** [comment]
>  - What do you mean they are way too low, and have a lot of unused space?
> Can you elaborate on that?

I'm talking about the way the artists tab is displayed way below the pink and the black stripe, shouldn't it be above? I don't really see the point of having that much unused space before the content of the page. In my opinion it should be directly below the "Check out your stats below".

**Comment by alexolivero** [comment]
Do you see the "Top Genres" and "Obscurity Rating" in the pink and black
stripe?

**Comment by Nezia1** [comment]
I didn't unfortunately, I disabled all my extensions and it's not showing.

**Comment by alexolivero** [comment]
You disabled all your extensions? What parts of the website do show for you?

**Comment by Nezia1** [comment]
The ones i sent you on the screenshot. I linked it on one of my comments.

**Comment by alexolivero** [comment]
Thanks for the screenshot, that's very helpful. We can get a fix soon.

Could you tell me what browser you're using, and if possible what version
of the browser?

**Comment by Nezia1** [comment]
I'm using Firefox 78.0.1 on Fedora.

**Comment by alexolivero** [comment]
Hello,
Believe this issue is fixed, could you please try again? Thanks a ton for bringing it up.

**Comment by Nezia1** [comment]
Thank you, it works well now!
